#pull image
FROM alpine:3

LABEL author="Bachtiar Firdaus"
LABEL github="https://github.com/bachtiar-firdaus" linkedIn="https://www.linkedin.com/in/bachtiar-firdaus-64b35419b/"

# testing copy
RUN mkdir hello
COPY text/*.txt hello

CMD cat "hello/world.txt"